# GitHub Dependabot configuration
# Note: there is no interaction between this
# configuration and dependabot security updates.
# See here for more information:
# https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/about-dependabot-security-updates#about-dependabot-security-updates

version: 2
updates:
  # GitHub Actions checks
  # See here for more information:
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  # Perform checks and updates for python poetry environment.
  # See here for more information:
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#pip-and-pip-compile
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates to poetry lockfile every week
      interval: "weekly"
