---
name: publish pypi release

on:
  release:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"
