---
name: run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # runs every Wednesday at 7 AM UTC
    - cron: "0 7 * * 3"

jobs:
  tests:
    strategy:
      matrix:
        # matrixed execution for parallel gh-action performance increases
        python_version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-24.04, macos-14]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Python setup
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Check lockfile
        run: uv lock --check
      - name: Install frozen environment
        run: uv sync --frozen --all-extras --group docs
      - name: Run sphinx-docs build test
        run: uv run --frozen sphinx-build docs/source doctest -W
      - name: Run pytest
        run: uv run --frozen pytest -m "not large_data_tests"
  # run large data tests as a separate job to help
  # conserve resources by detecting failure with
  # smaller tests first.
  run_large_data_tests:
    runs-on: ubuntu-24.04
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Python setup
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Check lockfile
        run: uv lock --check
      - name: Install frozen environment
        run: uv sync --frozen --all-extras
      - name: Run pytest for large data tests
        run: uv run --frozen pytest -m "large_data_tests"
